### PR TITLE
Wingthors contribs

### PR DESCRIPTION
**Pull request by baluballa**

### CODE REVIEW

**Comment by Delta-99** [comment]
I see potential problems with this commit. I'm not sure why there will a million commits included here. It almost seems like Wingthor branched from the wrong branch or something. 

Also I see changes to .gitignore and other files in the root I THINK that likely are mistaken or something else. And some other weirdness. I would be very hesitant to merge this.

I think all Wingthor was trying to do was add the one GRP-504 demo mission so that should be the only changes that come across in this merge.

What do you think @funkyfranky? It could be as simple as Wingthor re-branching and then just adding that directory and then merging again.

**Review by Delta-99 — CHANGES_REQUESTED** [review]
I left a comment on the merge request. Didn't know how to do this review properly so please read the comment there.

**Comment by baluballa** [comment]
I asked to commit to develop branch @Delta-99 the files changed is some local configuration files which is generated by git, eg gitignore and some config files VSC is creating. Many files where created when running Svens script. Its MIZ file unpacked.

**Comment by Delta-99** [comment]
> I asked to commit to develop branch @Delta-99 the files changed is some local configuration files which is generated by git, eg gitignore and some config files VSC is creating. Many files where created when running Svens script. Its MIZ file unpacked.

I just see way too many changes going on in various commits including your own. For example, you have wiped out README.md for unknown reasons.

Again, this just looks really dangerous and I don't see why your changes wouldn't just be with the one mission directory that you added. Further VSC may have made changes that shouldn't be committed. Unless you specifically added stuff to .gitignore for example I would not include those either OR you should just commit the directory ONLY.

I could be wrong but this is my opinion.

**Pull request closed without merging**
